; M5Recorder firmware for M5StickS3 (ESP32-S3-PICO-1-N8R8: 8 MB quad flash, 8 MB octal PSRAM)

[env:m5sticks3]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    !python version_flag.py

lib_deps =
    m5stack/M5Unified@0.2.24
    m5stack/M5GFX@0.2.31

monitor_speed = 115200
